### ISSUE TITLE
Safety

### ISSUE THREAD

**Issue by brillout** [yosbelms/remote-func#10]
I'm curious; how do you ensure that the JS query is safe to execute?

**Comment by yosbelms** [comment]
Hey @brillout thank for take your time to post here. Safety is the main challenge of this project. The general point of view is that the code is tree shaped data (referring to AST) and we can manipulate it to make it safe, you can read more [here](https://github.com/yosbelms/remote-func/blob/master/docs/query-function.md)

**Comment by brillout** [comment]
If I use a SQL database, a JS query is going to translate at some point or another to a set of SQL queries. Which means you'd need to ensure the safety of these SQL queries as well, I'm not sure how this is feasible.

One thing that would be interesting though is a database with JS as its query language. I don't like MongoDB; they made a poor job at tapping into the power of a turing complete language. Using a programming language as query language (wasm/JS/TS seems like a good candidate) could be simple and expressive(/powerful) at the same time.

For example, where you'd have full (but easy!) control over what get's indexed, e.g. materialized views defined with JS would be powerful and simple.

**Comment by yosbelms** [comment]
@brillout This project is about query endpoints, like GraphQL, or Falcor. That point of translation from Remote Func query to SQL is responsibility of the developer who makes the translation.

Currently I'm involved in a big personal project using Next.js, Remote Func, and PostgreSQL. I'm using [Slonik](https://github.com/gajus/slonik) for query DB which offers lot of safety.

> One thing that would be interesting though is a database with JS as its query language. 

I've been dreaming about making a JS frontend for PostgresSQL JSONB types, but time is lacking right now. Although, I think it should be very interesting project.

**Comment by yosbelms** [comment]
Also I've been experimenting by writing a very simple DB completely in JS, using JS for queries, but didn't decided to continue because the inefficiency of V8 (the JS engine) memory management.

PS: I love this idea

**Comment by brillout** [comment]
Okay I see.

`remove-func` is a radically different approach, never thought about something like this. Interesting.

Let's imagine GitHub exposes a new version of its API with `remote-func`. The GitHub API v4 is GraphQL and the v5 would be `remote-func`. Could you give an example where the v5 would be simpler to use than the v4?

My problem with GraphQL is it's (unecessary) complex server-side integration. But, as a user, GraphQL is actually neat. (Although I don't like GraphQL's query DSL.)

In general, I'm happy with declarative queries and I'm struggling to see the added benifit of a turing complete language to *define queries*. (Using JS to define models, indices, and materialized views would be on the other hand super neat.)

> Also I've been experimenting by writing a very simple DB completely in JS, using JS for queries

Neat...

I'm thinking more about using JS as an interface language; internally the DB could use Rust or whatever. Like MongoDB basically (interface is JS and internal code is C++).

A frontend is nothing else than a representation of database queries (and mutations). A DB that allows to define materialized views with JS would be powerful: the user clicks on the button -> the DB changes -> all materialized views update -> all frontend subscriptions update -> all frontend React views update. All of that done with JS alone.

> Currently I'm involved in a big personal project

If you don't mind me asking; what is this big personal project? I'm curious.

(Btw. I'm currently renaming Wildcad to `Telefunc`. It's kind of similar to `remote-func`, I hope it's ok with you? You were right `Wildcard API` is a bad name.)

**Comment by yosbelms** [comment]
> Could you give an example where the v5 would be simpler to use than the v4?

You can checkout the examples in the repo and compare it by yourself. I only recommend Remote-func by its simplicity and performance. GraphQL is getting fat, in my opinion. 

> If you don't mind me asking; what is this big personal project? I'm curious.

Only I can tell you that is devised to increase companies productivity ;)
