### ISSUE TITLE
JS queries VS declarative queries

### ISSUE THREAD

**Issue by brillout** [yosbelms/remote-func#11]
It's an interesting idea to use JS as a query language. It's nice to see someone exploring ideas.

But, my first reaction is that I wonder if it is that beneficial? Besides performance.

I would argue that declarative queries such as with GraphQL are often good enough. The need for something more powerful is not that common?

Maybe you are seeing things I'm not.

**Comment by yosbelms** [comment]
> I would argue that declarative queries such as with GraphQL are often good enough.

Whenever I see a new tool for the web the fist question that always comes to my mind is: How much this new tool takes from the web? Why it is needed a new language? Why a new protocol? Does the web currently has tools that can be used to solve this? and some other of the same kind.

Specifically about GraphQL I see some problems, for example:

1- Impedance Mismatch.
2- Unpredictable query cost.
3- N+1 queries, their work around this one using the called the Data Loader pattern that is not part of the GraphQL spec.

Last but not least, GraphQL is a NEW language. With JS you can write UI, server side code, CLI tools, database queries, and now you can query endpoints. With GraphQL, you can...., well, in the language field I see JS winning.

You can read more in [this article](https://dev.to/yosbelms/the-library-that-allows-to-use-javascript-as-the-query-language-for-your-api-j9m)

**Comment by brillout** [comment]
> Whenever I see a new tool for the web the fist question that always comes to my mind is: How much this new tool takes from the web? Why it is needed a new language? Why a new protocol? Does the web currently has tools that can be used to solve this? and some other of the same kind.

I wish more people would react like you do...

I agree about GraphQL. In general, I liked it at first but I got disappointed after a while.

Closing since I agree.
